services:
  web-app:
    build:
      context: .
    container_name: pelmeni_shop_back
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    env_file:
      - ./.env.dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#      sh -c "gunicorn shop_server.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database

  database:
    container_name: db_pelmeni
    image: postgres:14.6-alpine
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    container_name: pelmeni_celery_worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./server:/server
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./.env.dev

  beat:
    build:
      context: .
    hostname: beat
    container_name: pelmeni_celery_beat
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    volumes:
      - ./server:/server
    links:
      - redis
    depends_on:
      - redis
      - database
    env_file:
      - ./.env.dev

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./server:/server
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

#  front-app:
#    build:
#      context: ./front
#    container_name: pelmeni_shop_front
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./front:/front
#    depends_on:
#      - web-app

volumes:
  postgres_data:
