# Generated by Django 4.2.6 on 2023-10-06 21:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=50)),
                ('address_ZIP', models.CharField(max_length=10)),
                ('address_home_number', models.CharField(max_length=5)),
                ('img_manufacturer', models.ImageField(upload_to='author_img')),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hersteller',
                'verbose_name_plural': 'Hersteller',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('products_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_shipping', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNF', 'angenommen'), ('CON', 'bestätigt'), ('COL', 'gesammelt'), ('SHI', 'verschickt')], default='UNF', max_length=3)),
                ('payment_type', models.CharField(choices=[('PP', 'PayPal'), ('BG', 'Bar')], default='BG', max_length=2)),
                ('payment_status', models.CharField(choices=[('PAI', 'bezahlt'), ('UNP', 'unbezahlt')], default='UNP', max_length=3)),
                ('address_city', models.CharField(default='', max_length=20)),
                ('address_ZIP', models.CharField(default='', max_length=5)),
                ('address_street', models.CharField(default='', max_length=50)),
                ('address_home_number', models.CharField(default='', max_length=5)),
                ('address_last_name', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('templates', models.EmailField(default='', max_length=254)),
                ('invoice', models.FileField(null=True, upload_to='invoices')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(default='', max_length=150)),
                ('cooking', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('image', models.ImageField(upload_to='product_img')),
                ('amount', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('prepared', models.BooleanField(default=False)),
                ('vendor_code', models.CharField(default='9-', max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='product', to='shop.category')),
                ('composition', models.ManyToManyField(related_name='product', to='shop.composition')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
