# Generated by Django 4.2.6 on 2023-10-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
    ]
