# Generated by Django 4.2.6 on 2023-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shipment_remove_cart_ip_order_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
