# Generated by Django 4.2.6 on 2023-10-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_manufacturer_description_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='counting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='shop.category'),
        ),
    ]
