# Generated by Django 4.2.6 on 2023-10-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_counting_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.ManyToManyField(related_name='products', to='shop.composition'),
        ),
    ]
