# Generated by Django 4.2.6 on 2023-10-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prepared',
            new_name='is_price_for_one',
        ),
    ]
