# Generated by Django 4.2.6 on 2023-10-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_prepared_product_is_price_for_one'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user']},
        ),
    ]
