# Generated by Django 4.2.6 on 2023-11-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_doc',
            field=models.FileField(blank=True, null=True, upload_to='shipments'),
        ),
    ]
