# Generated by Django 4.2.6 on 2023-11-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shipment_shipment_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Bargeld', 'Bar')], default='Bargeld', max_length=10),
        ),
    ]
