# Generated by Django 4.2.6 on 2023-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PP', 'PayPal'), ('BG', 'Bargeld')], default='BG', max_length=3),
        ),
    ]
