# Generated by Django 4.2.6 on 2023-11-13 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('address_ZIP', models.CharField(blank=True, max_length=5, null=True, verbose_name='ZIP')),
                ('address_street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street')),
                ('address_home_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Home')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Name')),
                ('sum_orders', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price of all orders')),
                ('quantity_of_orders', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('favorite_product', models.ManyToManyField(blank=True, null=True, to='shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchaser',
                'verbose_name_plural': 'Purchasers',
                'ordering': ['user'],
            },
        ),
    ]
