# Generated by Django 4.2.6 on 2023-10-06 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='City')),
                ('address_ZIP', models.CharField(blank=True, max_length=5, null=True, verbose_name='ZIP')),
                ('address_street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street')),
                ('address_home_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Home')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Name')),
                ('favorite_product', models.ManyToManyField(blank=True, null=True, to='shop.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['user'],
            },
        ),
    ]
