# Generated by Django 4.2.6 on 2023-10-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaser',
            options={'ordering': ['user'], 'verbose_name': 'Purchaser', 'verbose_name_plural': 'Purchasers'},
        ),
    ]
