# Generated by Django 4.2.6 on 2023-10-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0002_alter_purchaser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
