# Generated by Django 4.2.6 on 2023-10-30 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0003_purchaser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaser',
            name='quantity_of_oder',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='sum_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
