# Generated by Django 4.2.6 on 2023-10-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0004_purchaser_quantity_of_oder_purchaser_sum_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaser',
            old_name='quantity_of_oder',
            new_name='quantity_of_oders',
        ),
    ]
