# Generated by Django 4.2.6 on 2023-10-30 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaser', '0006_rename_quantity_of_oders_purchaser_quantity_of_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='quantity_of_orders',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price of all orders'),
        ),
    ]
